<?php

namespace Database\Seeders;

use App\Models\Citie; 
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Citie::insert([
            ['id' => 1, 'city' => 'Aïn Harrouda'],
            ['id' => 2, 'city' => 'Ben Yakhlf'],
            ['id' => 3, 'city' => 'Bouskoura'],
            ['id' => 4, 'city' => 'Casablanca'],
            ['id' => 5, 'city' => 'Médiouna'],
            ['id' => 6, 'city' => 'Mohammadia'],
            ['id' => 7, 'city' => 'Tit Mellil'],
            ['id' => 8, 'city' => 'Ben Yakhlef'],
            ['id' => 9, 'city' => 'Bejaâd'],
            ['id' => 10, 'city' => 'Ben Ahmed'],
            ['id' => 11, 'city' => 'Benslimane'],
            ['id' => 12, 'city' => 'Berrechid'],
            ['id' => 13, 'city' => 'Boujniba'],
            ['id' => 14, 'city' => 'Boulanouare'],
            ['id' => 15, 'city' => 'Bouznika'],
            ['id' => 16, 'city' => 'Deroua'],
            ['id' => 17, 'city' => 'El Borouj'],
            ['id' => 18, 'city' => 'El Gara'],
            ['id' => 19, 'city' => 'Guisser'],
            ['id' => 20, 'city' => 'Hattane'],
            ['id' => 21, 'city' => 'Khouribga'],
            ['id' => 22, 'city' => 'Loulad'],
            ['id' => 23, 'city' => 'Oued Zem'],
            ['id' => 24, 'city' => 'Oulad Abbou'],
            ['id' => 25, 'city' => 'Oulad HRiz Sahel'],
            ['id' => 26, 'city' => 'Oulad Mrah'],
            ['id' => 27, 'city' => 'Oulad Saïd'],
            ['id' => 28, 'city' => 'Oulad Sidi Ben Daoud'],
            ['id' => 29, 'city' => 'Ras El Aïn'],
            ['id' => 30, 'city' => 'Settat'],
            ['id' => 31, 'city' => 'Sidi Rahhal Chataï'],
            ['id' => 32, 'city' => 'Soualem'],
            ['id' => 33, 'city' => 'Azemmour'],
            ['id' => 34, 'city' => 'Bir Jdid'],
            ['id' => 35, 'city' => 'Bouguedra'],
            ['id' => 36, 'city' => 'Echemmaia'],
            ['id' => 37, 'city' => 'El Jadida'],
            ['id' => 38, 'city' => 'Hrara'],
            ['id' => 39, 'city' => 'Ighoud'],
            ['id' => 40, 'city' => 'Jamâat Shaim'],
            ['id' => 41, 'city' => 'Jorf Lasfar'],
            ['id' => 42, 'city' => 'Khemis Zemamra'],
            ['id' => 43, 'city' => 'Laaounate'],
            ['id' => 44, 'city' => 'Moulay Abdallah'],
            ['id' => 45, 'city' => 'Oualidia'],
            ['id' => 46, 'city' => 'Oulad Amrane'],
            ['id' => 47, 'city' => 'Oulad Frej'],
            ['id' => 48, 'city' => 'Oulad Ghadbane'],
            ['id' => 49, 'city' => 'Safi'],
            ['id' => 50, 'city' => 'Sebt El Maârif'],
            ['id' => 51, 'city' => 'Sebt Gzoula'],
            ['id' => 52, 'city' => 'Sidi Ahmed'],
            ['id' => 53, 'city' => 'Sidi Ali Ban Hamdouche'],
            ['id' => 54, 'city' => 'Sidi Bennour'],
            ['id' => 55, 'city' => 'Sidi Bouzid'],
            ['id' => 56, 'city' => 'Sidi Smaïl'],
            ['id' => 57, 'city' => 'Youssoufia'],
            ['id' => 58, 'city' => 'Fès'],
            ['id' => 59, 'city' => 'Aïn Cheggag'],
            ['id' => 60, 'city' => 'Bhalil'],
            ['id' => 61, 'city' => 'Boulemane'],
            ['id' => 62, 'city' => 'El Menzel'],
            ['id' => 63, 'city' => 'Guigou'],
            ['id' => 64, 'city' => 'Imouzzer Kandar'],
            ['id' => 65, 'city' => 'Imouzzer Marmoucha'],
            ['id' => 66, 'city' => 'Missour'],
            ['id' => 67, 'city' => 'Moulay Yaâcoub'],
            ['id' => 68, 'city' => 'Ouled Tayeb'],
            ['id' => 69, 'city' => 'Outat El Haj'],
            ['id' => 70, 'city' => 'Ribate El Kheir'],
            ['id' => 71, 'city' => 'Séfrou'],
            ['id' => 72, 'city' => 'Skhinate'],
            ['id' => 73, 'city' => 'Tafajight'],
            ['id' => 74, 'city' => 'Arbaoua'],
            ['id' => 75, 'city' => 'Aïn Dorij'],
            ['id' => 76, 'city' => 'Dar Gueddari'],
            ['id' => 77, 'city' => 'Had Kourt'],
            ['id' => 78, 'city' => 'Jorf El Melha'],
            ['id' => 79, 'city' => 'Kénitra'],
            ['id' => 80, 'city' => 'Khenichet'],
            ['id' => 81, 'city' => 'Lalla Mimouna'],
            ['id' => 82, 'city' => 'Mechra Bel Ksiri'],
            ['id' => 83, 'city' => 'Mehdia'],
            ['id' => 84, 'city' => 'Moulay Bousselham'],
            ['id' => 85, 'city' => 'Sidi Allal Tazi'],
            ['id' => 86, 'city' => 'Sidi Kacem'],
            ['id' => 87, 'city' => 'Sidi Slimane'],
            ['id' => 88, 'city' => 'Sidi Taibi'],
            ['id' => 89, 'city' => 'Sidi Yahya El Gharb'],
            ['id' => 90, 'city' => 'Souk El Arbaa'],
            ['id' => 91, 'city' => 'Akka'],
            ['id' => 92, 'city' => 'Assa'],
            ['id' => 93, 'city' => 'Bouizakarne'],
            ['id' => 94, 'city' => 'El Ouatia'],
            ['id' => 95, 'city' => 'Es-Semara'],
            ['id' => 96, 'city' => 'Fam El Hisn'],
            ['id' => 97, 'city' => 'Foum Zguid'],
            ['id' => 98, 'city' => 'Guelmim'],
            ['id' => 99, 'city' => 'Taghjijt'],
            ['id' => 100, 'city' => 'Tan-Tan'],
            ['id' => 101, 'city' => 'Tata'],
            ['id' => 102, 'city' => 'Zag'],
            ['id' => 103, 'city' => 'Marrakech'],
            ['id' => 104, 'city' => 'Ait Daoud'],
            ['id' => 115, 'city' => 'Amizmiz'],
            ['id' => 116, 'city' => 'Assahrij'],
            ['id' => 117, 'city' => 'Aït Ourir'],
            ['id' => 118, 'city' => 'Ben Guerir'],
            ['id' => 119, 'city' => 'Chichaoua'],
            ['id' => 120, 'city' => 'El Hanchane'],
            ['id' => 121, 'city' => 'El Kelaâ des Sraghna'],
            ['id' => 122, 'city' => 'Essaouira'],
            ['id' => 123, 'city' => 'Fraïta'],
            ['id' => 124, 'city' => 'Ghmate'],
            ['id' => 125, 'city' => 'Ighounane'],
            ['id' => 126, 'city' => 'Imintanoute'],
            ['id' => 127, 'city' => 'Kattara'],
            ['id' => 128, 'city' => 'Lalla Takerkoust'],
            ['id' => 129, 'city' => 'Loudaya'],
            ['id' => 130, 'city' => 'Lâattaouia'],
            ['id' => 131, 'city' => 'Moulay Brahim'],
            ['id' => 132, 'city' => 'Mzouda'],
            ['id' => 133, 'city' => 'Ounagha'],
            ['id' => 134, 'city' => 'Sid LMokhtar'],
            ['id' => 135, 'city' => 'Sid Zouin'],
            ['id' => 136, 'city' => 'Sidi Abdallah Ghiat'],
            ['id' => 137, 'city' => 'Sidi Bou Othmane'],
            ['id' => 138, 'city' => 'Sidi Rahhal'],
            ['id' => 139, 'city' => 'Skhour Rehamna'],
            ['id' => 140, 'city' => 'Smimou'],
            ['id' => 141, 'city' => 'Tafetachte'],
            ['id' => 142, 'city' => 'Tahannaout'],
            ['id' => 143, 'city' => 'Talmest'],
            ['id' => 144, 'city' => 'Tamallalt'],
            ['id' => 145, 'city' => 'Tamanar'],
            ['id' => 146, 'city' => 'Tamansourt'],
            ['id' => 147, 'city' => 'Tameslouht'],
            ['id' => 148, 'city' => 'Tanalt'],
            ['id' => 149, 'city' => 'Zeubelemok'],
            ['id' => 150, 'city' => 'Meknès'],
            ['id' => 151, 'city' => 'Khénifra'],
            ['id' => 152, 'city' => 'Agourai'],
            ['id' => 153, 'city' => 'Ain Taoujdate'],
            ['id' => 154, 'city' => 'MyAliCherif'],
            ['id' => 155, 'city' => 'Rissani'],
            ['id' => 156, 'city' => 'Amalou Ighriben'],
            ['id' => 157, 'city' => 'Aoufous'],
            ['id' => 158, 'city' => 'Arfoud'],
            ['id' => 159, 'city' => 'Azrou'],
            ['id' => 160, 'city' => 'Aïn Jemaa'],
            ['id' => 161, 'city' => 'Aïn Karma'],
            ['id' => 162, 'city' => 'Aïn Leuh'],
            ['id' => 163, 'city' => 'Aït Boubidmane'],
            ['id' => 164, 'city' => 'Aït Ishaq'],
            ['id' => 165, 'city' => 'Boudnib'],
            ['id' => 166, 'city' => 'Boufakrane'],
            ['id' => 167, 'city' => 'Boumia'],
            ['id' => 168, 'city' => 'El Hajeb'],
            ['id' => 169, 'city' => 'Elkbab'],
            ['id' => 170, 'city' => 'Er-Rich'],
            ['id' => 171, 'city' => 'Errachidia'],
            ['id' => 172, 'city' => 'Gardmit'],
            ['id' => 173, 'city' => 'Goulmima'],
            ['id' => 174, 'city' => 'Gourrama'],
            ['id' => 175, 'city' => 'Had Bouhssoussen'],
            ['id' => 176, 'city' => 'Haj Kaddour'],
            ['id' => 177, 'city' => 'Ifrane'],
            ['id' => 178, 'city' => 'Itzer'],
            ['id' => 179, 'city' => 'Jorf'],
            ['id' => 180, 'city' => 'Kehf Nsour'],
            ['id' => 181, 'city' => 'Kerrouchen'],
            ['id' => 182, 'city' => 'Mhaya'],
            ['id' => 183, 'city' => 'Mrirt'],
            ['id' => 184, 'city' => 'Midelt'],
            ['id' => 185, 'city' => 'Moulay Ali Cherif'],
            ['id' => 186, 'city' => 'Moulay Bouazza'],
            ['id' => 187, 'city' => 'Moulay Idriss Zerhoun'],
            ['id' => 188, 'city' => 'Moussaoua'],
            ['id' => 189, 'city' => 'N\'Zalat Bni Amar'],
            ['id' => 190, 'city' => 'Ouaoumana'],
            ['id' => 191, 'city' => 'Oued Ifrane'],
            ['id' => 192, 'city' => 'Sabaa Aiyoun'],
            ['id' => 193, 'city' => 'Sebt Jahjouh'],
            ['id' => 194, 'city' => 'Sidi Addi'],
            ['id' => 195, 'city' => 'Tichoute'],
            ['id' => 196, 'city' => 'Tighassaline'],
            ['id' => 197, 'city' => 'Tighza'],
            ['id' => 198, 'city' => 'Timahdite'],
            ['id' => 199, 'city' => 'Tinejdad'],
            ['id' => 200, 'city' => 'Tizguite'],
            ['id' => 201, 'city' => 'Toulal'],
            ['id' => 202, 'city' => 'Tounfite'],
            ['id' => 203, 'city' => 'Zaouia d\'Ifrane'],
            ['id' => 204, 'city' => 'Zaïda'],
            ['id' => 205, 'city' => 'Ahfir'],
            ['id' => 206, 'city' => 'Aklim'],
            ['id' => 207, 'city' => 'Al Aroui'],
            ['id' => 208, 'city' => 'Aïn Bni Mathar'],
            ['id' => 209, 'city' => 'Aïn Erreggada'],
            ['id' => 210, 'city' => 'Ben Taïeb'],
            ['id' => 211, 'city' => 'Berkane'],
            ['id' => 212, 'city' => 'Bni Ansar'],
            ['id' => 213, 'city' => 'Bni Chiker'],
            ['id' => 214, 'city' => 'Bni Drar'],
            ['id' => 215, 'city' => 'Bni Tadjite'],
            ['id' => 216, 'city' => 'Bouanane'],
            ['id' => 217, 'city' => 'Bouarfa'],
            ['id' => 218, 'city' => 'Bouhdila'],
            ['id' => 219, 'city' => 'Dar El Kebdani'],
            ['id' => 220, 'city' => 'Debdou'],
            ['id' => 221, 'city' => 'Douar Kannine'],
            ['id' => 222, 'city' => 'Driouch'],
            ['id' => 223, 'city' => 'El Aïoun Sidi Mellouk'],
            ['id' => 224, 'city' => 'Farkhana'],
            ['id' => 225, 'city' => 'Figuig'],
            ['id' => 226, 'city' => 'Ihddaden'],
            ['id' => 227, 'city' => 'Jaâdar'],
            ['id' => 228, 'city' => 'Jerada'],
            ['id' => 229, 'city' => 'Kariat Arekmane'],
            ['id' => 230, 'city' => 'Kassita'],
            ['id' => 231, 'city' => 'Kerouna'],
            ['id' => 232, 'city' => 'Laâtamna'],
            ['id' => 233, 'city' => 'Madagh'],
            ['id' => 234, 'city' => 'Midar'],
            ['id' => 235, 'city' => 'Nador'],
            ['id' => 236, 'city' => 'Naima'],
            ['id' => 237, 'city' => 'Oued Heimer'],
            ['id' => 238, 'city' => 'Oujda'],
            ['id' => 239, 'city' => 'Ras El Ma'],
            ['id' => 240, 'city' => 'Saïdia'],
            ['id' => 241, 'city' => 'Selouane'],
            ['id' => 242, 'city' => 'Sidi Boubker'],
            ['id' => 243, 'city' => 'Sidi Slimane Echcharaa'],
            ['id' => 244, 'city' => 'Talsint'],
            ['id' => 245, 'city' => 'Taourirt'],
            ['id' => 246, 'city' => 'Tendrara'],
            ['id' => 247, 'city' => 'Tiztoutine'],
            ['id' => 248, 'city' => 'Touima'],
            ['id' => 249, 'city' => 'Touissit'],
            ['id' => 250, 'city' => 'Zaïo'],
            ['id' => 251, 'city' => 'Zeghanghane'],
            ['id' => 252, 'city' => 'Rabat'],
            ['id' => 253, 'city' => 'Salé'],
            ['id' => 254, 'city' => 'Ain El Aouda'],
            ['id' => 255, 'city' => 'Harhoura'],
            ['id' => 256, 'city' => 'Khémisset'],
            ['id' => 257, 'city' => 'Oulmès'],
            ['id' => 258, 'city' => 'Rommani'],
            ['id' => 259, 'city' => 'Sidi Allal El Bahraoui'],
            ['id' => 260, 'city' => 'Sidi Bouknadel'],
            ['id' => 261, 'city' => 'Skhirate'],
            ['id' => 262, 'city' => 'Tamesna'],
            ['id' => 263, 'city' => 'Témara'],
            ['id' => 264, 'city' => 'Tiddas'],
            ['id' => 265, 'city' => 'Tiflet'],
            ['id' => 266, 'city' => 'Touarga'],
            ['id' => 267, 'city' => 'Agadir'],
            ['id' => 268, 'city' => 'Agdz'],
            ['id' => 269, 'city' => 'Agni Izimmer'],
            ['id' => 270, 'city' => 'Aït Melloul'],
            ['id' => 271, 'city' => 'Alnif'],
            ['id' => 272, 'city' => 'Anzi'],
            ['id' => 273, 'city' => 'Aoulouz'],
            ['id' => 274, 'city' => 'Aourir'],
            ['id' => 275, 'city' => 'Arazane'],
            ['id' => 276, 'city' => 'Aït Baha'],
            ['id' => 277, 'city' => 'Aït Iaâza'],
            ['id' => 278, 'city' => 'Aït Yalla'],
            ['id' => 279, 'city' => 'Ben Sergao'],
            ['id' => 280, 'city' => 'Biougra'],
            ['id' => 281, 'city' => 'Boumalne-Dadès'],
            ['id' => 282, 'city' => 'Dcheira El Jihadia'],
            ['id' => 283, 'city' => 'Drargua'],
            ['id' => 284, 'city' => 'El Guerdane'],
            ['id' => 285, 'city' => 'Harte Lyamine'],
            ['id' => 286, 'city' => 'Ida Ougnidif'],
            ['id' => 287, 'city' => 'Ifri'],
            ['id' => 288, 'city' => 'Igdamen'],
            ['id' => 289, 'city' => 'Ighil n\'Oumgoun'],
            ['id' => 290, 'city' => 'Imassine'],
            ['id' => 291, 'city' => 'Inezgane'],
            ['id' => 292, 'city' => 'Irherm'],
            ['id' => 293, 'city' => 'Kelaat-M\'Gouna'],
            ['id' => 294, 'city' => 'Lakhsas'],
            ['id' => 295, 'city' => 'Lakhsass'],
            ['id' => 296, 'city' => 'Lqliâa'],
            ['id' => 297, 'city' => 'M\'semrir'],
            ['id' => 298, 'city' => 'Massa (Ma)'],
            ['id' => 299, 'city' => 'Megousse'],
            ['id' => 300, 'city' => 'Ouarzazate'],
            ['id' => 301, 'city' => 'Oulad Berhil'],
            ['id' => 302, 'city' => 'Oulad Teïma'],
            ['id' => 303, 'city' => 'Sarghine'],
            ['id' => 304, 'city' => 'Sidi Ifni'],
            ['id' => 305, 'city' => 'Skoura'],
            ['id' => 306, 'city' => 'Tabounte'],
            ['id' => 307, 'city' => 'Tafraout'],
            ['id' => 308, 'city' => 'Taghzout'],
            ['id' => 309, 'city' => 'Tagzen'],
            ['id' => 310, 'city' => 'Taliouine'],
            ['id' => 311, 'city' => 'Tamegroute'],
            ['id' => 312, 'city' => 'Tamraght'],
            ['id' => 313, 'city' => 'Tanoumrite Nkob Zagora'],
            ['id' => 314, 'city' => 'Taourirt ait zaghar'],
            ['id' => 315, 'city' => 'Taroudannt'],
            ['id' => 316, 'city' => 'Temsia'],
            ['id' => 317, 'city' => 'Tifnit'],
            ['id' => 318, 'city' => 'Tisgdal'],
            ['id' => 319, 'city' => 'Tiznit'],
            ['id' => 320, 'city' => 'Toundoute'],
            ['id' => 321, 'city' => 'Zagora'],
            ['id' => 322, 'city' => 'Afourar'],
            ['id' => 323, 'city' => 'Aghbala'],
            ['id' => 324, 'city' => 'Azilal'],
            ['id' => 325, 'city' => 'Aït Majden'],
            ['id' => 326, 'city' => 'Beni Ayat'],
            ['id' => 327, 'city' => 'Béni Mellal'],
            ['id' => 328, 'city' => 'Bin elouidane'],
            ['id' => 329, 'city' => 'Bradia'],
            ['id' => 330, 'city' => 'Bzou'],
            ['id' => 331, 'city' => 'Dar Oulad Zidouh'],
            ['id' => 332, 'city' => 'Demnate'],
            ['id' => 333, 'city' => 'Dra\'a'],
            ['id' => 334, 'city' => 'El Ksiba'],
            ['id' => 335, 'city' => 'Foum Jamaa'],
            ['id' => 336, 'city' => 'Fquih Ben Salah'],
            ['id' => 337, 'city' => 'Kasba Tadla'],
            ['id' => 338, 'city' => 'Ouaouizeght'],
            ['id' => 339, 'city' => 'Oulad Ayad'],
            ['id' => 340, 'city' => 'Oulad M\'Barek'],
            ['id' => 341, 'city' => 'Oulad Yaich'],
            ['id' => 342, 'city' => 'Sidi Jaber'],
            ['id' => 343, 'city' => 'Souk Sebt Oulad Nemma'],
            ['id' => 344, 'city' => 'Zaouïat Cheikh'],
            ['id' => 345, 'city' => 'Tanger'],
            ['id' => 346, 'city' => 'Tétouan'],
            ['id' => 347, 'city' => 'Akchour'],
            ['id' => 348, 'city' => 'Assilah'],
            ['id' => 349, 'city' => 'Bab Berred'],
            ['id' => 350, 'city' => 'Bab Taza'],
            ['id' => 351, 'city' => 'Brikcha'],
            ['id' => 352, 'city' => 'Chefchaouen'],
            ['id' => 353, 'city' => 'Dar Bni Karrich'],
            ['id' => 354, 'city' => 'Dar Chaoui'],
            ['id' => 355, 'city' => 'Fnideq'],
            ['id' => 356, 'city' => 'Gueznaia'],
            ['id' => 357, 'city' => 'Jebha'],
            ['id' => 358, 'city' => 'Karia'],
            ['id' => 359, 'city' => 'Khémis Sahel'],
            ['id' => 360, 'city' => 'Ksar El Kébir'],
            ['id' => 361, 'city' => 'Larache'],
            ['id' => 362, 'city' => 'M\'diq'],
            ['id' => 363, 'city' => 'Martil'],
            ['id' => 364, 'city' => 'Moqrisset'],
            ['id' => 365, 'city' => 'Oued Laou'],
            ['id' => 366, 'city' => 'Oued Rmel'],
            ['id' => 367, 'city' => 'Ouazzane'],
            ['id' => 368, 'city' => 'Point Cires'],
            ['id' => 369, 'city' => 'Sidi Lyamani'],
            ['id' => 370, 'city' => 'Sidi Mohamed ben Abdallah el-Raisuni'],
            ['id' => 371, 'city' => 'Zinat'],
            ['id' => 372, 'city' => 'Ajdir'],
            ['id' => 373, 'city' => 'Aknoul'],
            ['id' => 374, 'city' => 'Al Hoceïma'],
            ['id' => 375, 'city' => 'Aït Hichem'],
            ['id' => 376, 'city' => 'Bni Bouayach'],
            ['id' => 377, 'city' => 'Bni Hadifa'],
            ['id' => 378, 'city' => 'Ghafsai'],
            ['id' => 379, 'city' => 'Guercif'],
            ['id' => 380, 'city' => 'Imzouren'],
            ['id' => 381, 'city' => 'Inahnahen'],
            ['id' => 382, 'city' => 'Issaguen (Ket)'],
            ['id' => 383, 'city' => 'Karia (El Jad)'],
            ['id' => 384, 'city' => 'Karia Ba Mohamed'],
            ['id' => 385, 'city' => 'Oued Amlil'],
            ['id' => 386, 'city' => 'Oulad Zbair'],
            ['id' => 387, 'city' => 'Tahla'],
            ['id' => 388, 'city' => 'Tala Tazegwaght'],
            ['id' => 389, 'city' => 'Tamassint'],
            ['id' => 390, 'city' => 'Taounate'],
            ['id' => 391, 'city' => 'Targuist'],
            ['id' => 392, 'city' => 'Taza'],
            ['id' => 393, 'city' => 'Taïnaste'],
            ['id' => 394, 'city' => 'Thar Es-Souk'],
            ['id' => 395, 'city' => 'Tissa'],
            ['id' => 396, 'city' => 'Tizi Ouasli'],
            ['id' => 397, 'city' => 'Laayoune,'],
            ['id' => 398, 'city' => 'El Marsa'],
            ['id' => 399, 'city' => 'Tarfaya'],
            ['id' => 400, 'city' => 'Boujdour'],
            ['id' => 401, 'city' => 'Awsard'],
            ['id' => 402, 'city' => 'Oued-Eddahab'],
            ['id' => 403, 'city' => 'Stehat'],
            ['id' => 404, 'city' => 'Aït Attab'],
                            
    ]);
}

    }

